name: yonnkomi

options:
  bundleIdPrefix: app.takaoka.harusuke
  deploymentTarget:
    iOS: "17.5"
  developmentLanguage: en
  xcodeVersion: "15.4"
  createIntermediateGroups: true

packages:
  FirebaseSDK:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 12.0.0
  Cloudinary:
    url: https://github.com/cloudinary/cloudinary_ios.git
    from: 5.2.3
  PKHUD:
    url: https://github.com/pkluz/PKHUD.git
    from: 5.4.0

targets:
  yonnkomi:
    type: application
    platform: iOS

    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: "\"yonnkomi/Preview Content\""
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        GENERATE_INFOPLIST_FILE: true

    sources:
      - path: yonnkomi
        excludes:
          - "*.xcodeproj"
          - "*.xcworkspace"

    dependencies:
      - package: FirebaseSDK
        product: FirebaseAuth
      - package: FirebaseSDK
        product: FirebaseCore
      - package: FirebaseSDK
        product: FirebaseDatabase
      - package: FirebaseSDK
        product: FirebaseFirestore
      - package: FirebaseSDK
        product: FirebaseStorage
      - package: Cloudinary
        product: Cloudinary
      - package: PKHUD
        product: PKHUD
